src/Entity/DemandeAvance.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DemandeAvanceRepository")
 */
class DemandeAvance
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Collaborateur", inversedBy="demandeAvances")
     * @ORM\JoinColumn(nullable=false)
     */
    private $collabo;

    /**
     * @ORM\Column(type="float")
     */
    private $montant;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LigneDeFrais", mappedBy="demandeAvance")
     */
    private $Lignes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statut;

    /**
     * @ORM\Column(type="string", length=1024, nullable=true)
     */
    private $Motif;

    /**
     * @ORM\Column(type="datetime")
     */
    private $lastModif;

    const STATUS= [
        0 => 'En cours de validation',
        1 => 'Validee',
        2 => 'Refusee',
    ];

    public function __construct()
    {
        $this->Lignes = new ArrayCollection();
        $this->setStatut(DemandeAvance::STATUS[0]);
        $this->lastModif = new \DateTime();
        $this->setMontant(0);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCollabo(): ?Collaborateur
    {
        return $this->collabo;
    }

    public function setCollabo(?Collaborateur $collabo): self
    {
        $this->collabo = $collabo;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    /**
     * @return Collection|LigneDeFrais[]
     */
    public function getLignes(): Collection
    {
        return $this->Lignes;
    }

    public function addLigne(LigneDeFrais $ligne): self
    {
        if (!$this->Lignes->contains($ligne)) {
            $this->Lignes[] = $ligne;
            $ligne->setDemandeAvance($this);
        }

        return $this;
    }

    public function removeLigne(LigneDeFrais $ligne): self
    {
        if ($this->Lignes->contains($ligne)) {
            $this->Lignes->removeElement($ligne);
            // set the owning side to null (unless already changed)
            if ($ligne->getDemandeAvance() === $this) {
                $ligne->setDemandeAvance(null);
            }
        }

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getMotif(): ?string
    {
        return $this->Motif;
    }

    public function setMotif(?string $Motif): self
    {
        $this->Motif = $Motif;

        return $this;
    }

    public function getLastModif(): ?\DateTimeInterface
    {
        return $this->lastModif;
    }

    public function setLastModif(\DateTimeInterface $lastModif): self
    {
        $this->lastModif = $lastModif;

        return $this;
    }
}

src/Entity/LigneDeFrais.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\DateType;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LigneDeFraisRepository")
 */
class LigneDeFrais
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    private $intitule;

    /**
     * @ORM\Column(type="string", length=2048)
     */
    private $mission;

    /**
     * @ORM\Column(type="float")
     */
    private $montant;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statutValidation;

    /**
     * @ORM\Column(type="boolean")
     */
    private $avance;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\NoteDeFrais")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Note;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Projet")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Projet;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastModif;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="array")
     */
    private $justificatif = [];

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $montantAvance;

    const STATUS = [
        0 => 'En cours',
        1 => 'En attente chef',
        2 => 'validee chef',
        3 => 'refusee chef',
        4 => 'En attente compta', #NOT USED
        5 => 'validee compta',
        6 => 'valideeExceptJustificatif',
        7 => 'refusee compta',
    ];

    public function __construct()
    {
      $this->statutValidation = "Non validée";
      $this->lastModif = new \DateTime();
      $this->avance = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): self
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getMission(): ?string
    {
        return $this->mission;
    }

    public function setMission(string $mission): self
    {
        $this->mission = $mission;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStatutValidation(): ?string
    {
        return $this->statutValidation;
    }

    public function setStatutValidation(string $statutValidation): self
    {
        $this->statutValidation = $statutValidation;

        return $this;
    }

    public function getAvance(): ?bool
    {
        return $this->avance;
    }

    public function setAvance(bool $avance): self
    {
        $this->avance = $avance;

        return $this;
    }

    public function getNote(): ?NoteDeFrais
    {
        return $this->Note;
    }

    public function setNote(?NoteDeFrais $Note): self
    {
        $this->Note = $Note;

        return $this;
    }

    public function getProjet(): ?Projet
    {
        return $this->Projet;
    }

    public function setProjet(?Projet $Projet): self
    {
        $this->Projet = $Projet;

        return $this;
    }

    public function getLastModif(): ?\DateTimeInterface
    {
        return $this->lastModif;
    }

    public function setLastModif(?\DateTimeInterface $lastModif): self
    {
        $this->lastModif = $lastModif;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getJustificatif(): ?array
    {
        return $this->justificatif;
    }

    public function setJustificatif(array $justificatif): self
    {
        $this->justificatif = $justificatif;

        return $this;
    }

    public function isModifiable(): ?bool
    {
        if(                                    $this->statutValidation == LigneDeFrais::STATUS[0] 
                                            || $this->statutValidation == LigneDeFrais::STATUS[3]
                                            || $this->statutValidation == LigneDeFrais::STATUS[7]
                                            || $this->statutValidation == LigneDeFrais::STATUS[6]){
            return true;
        }
        return false;
    }

    public function getMontantAvance(): ?float
    {
        return $this->montantAvance;
    }

    public function setMontantAvance(?float $montantAvance): self
    {
        $this->montantAvance = $montantAvance;

        return $this;
    }
}

src/Entity/Projet.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjetRepository")
 */
class Projet
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=512)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=2048, nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="date")
     */
    private $DateDebut;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $DateFin;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Collaborateur")
     */
    private $collabos;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Service")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Service;

    const STATUS = [
        0 => 'A venir',
        1 => 'En cours',
        2 => 'Suspendu',
        3 => 'Fini',
    ];

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    public function __construct()
    {
        $this->collabos = new ArrayCollection();
        $this->setStatus(Projet::STATUS[0]);
        $this->setDescription('Pas de description.');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(?\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }

    /**
     * @return Collection|Collaborateur[]
     */
    public function getCollabos(): Collection
    {
        return $this->collabos;
    }

    public function addCollabo(Collaborateur $collabo): self
    {
        if (!$this->collabos->contains($collabo)) {
            $this->collabos[] = $collabo;
            $collabo->addProjet($this);

        }

        return $this;
    }

    public function removeCollabo(Collaborateur $collabo): self
    {
        if ($this->collabos->contains($collabo)) {
            $this->collabos->removeElement($collabo);
        }

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->Service;
    }

    public function setService(?Service $Service): self
    {
        $this->Service = $Service;

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;
        return $this;
    }
}

src/Entity/Service.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
 * @ORM\Entity(repositoryClass="App\Repository\ServiceRepository")
 * @UniqueEntity("nom")
 */
class Service
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    private $nom;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Collaborateur")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Chef;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Conge", mappedBy="service")
     */
    private $conges;

    public function __construct()
    {
        $this->conges = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getChef(): ?Collaborateur
    {
        return $this->Chef;
    }

    public function setChef(?Collaborateur $Chef): self
    {
        $this->Chef = $Chef;

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }

    /**
     * @return Collection|Conge[]
     */
    public function getConges(): Collection
    {
        return $this->conges;
    }

    public function addConge(Conge $conge): self
    {
        if (!$this->conges->contains($conge)) {
            $this->conges[] = $conge;
            $conge->setService($this);
        }

        return $this;
    }

    public function removeConge(Conge $conge): self
    {
        if ($this->conges->contains($conge)) {
            $this->conges->removeElement($conge);
            // set the owning side to null (unless already changed)
            if ($conge->getService() === $this) {
                $conge->setService(null);
            }
        }

        return $this;
    }
}

templates/pages/gestionCongesChef.html.twig
{% extends 'topBar.html.twig' %}
{% block title %}Gestion des congés{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="js/plugins/fullcalendar/css/fullcalendar.min.css" type="text/css">
{% endblock %}

{% block body %}
        {% set salarie = null %}
        <div class="row">
            <div class="col s12 m8 l8">
                <div id='calendar'>

                </div>
            </div>
            <div class="col s12 m4 l4">
                <ul class="tabs">
                    <li class="tab col s6"><a class="active" href="#demandesEnCours">Demandes en cours</a></li>
                    <li class="tab col s6"><a href="#HistoriqueDemandes">Historique des demandes</a></li>
                </ul>
                <div id="demandesEnCours" class="col s12">
                    {% if congesEnAttente == null %}
                        Il n'y a aucune demande en attente
                    {% else %}
                        {% for demande in congesEnAttente %}
                            <ul class="collapsible">
                                <li>
                                    <div class="collapsible-header" style="display: block">
                                        <div class="right">
                                            <img class="responsive-img"  height="50" width="50" src="{{ demande.collabo.profile_pic_path }}"/>
                                        </div>
                                        {{ demande.collabo.prenom }} {{ demande.collabo.nom }} <br>
                                        {{ demande.type }} <br>
                                        {{ demande.date_debut|date('d/m/Y') }} - {{ demande.date_fin|date('d/m/Y') }}

                                    </div>
                                    <div class="collapsible-body">
                                        Demi-journées restantes : {{ demande.collabo.conge }} <br><br>
                                        <form action="{{ path('valider.conges.chef') }}" method="post">
                                            <input type="hidden" name="decision" id="decision{{ demande.id_conge }}" value=""/>
                                            <input type="hidden" name="demande" value="{{ demande.id_conge }}"/>


                                            <button type="submit" onclick="$('#decision'+{{ demande.id_conge }}).val('valider');" class="waves-effect waves-light btn-small green" style="margin:auto;">Valider</button>
                                        </form>
                                        <a class="waves-effect waves-light btn modalRefus modal-trigger red" data-id="{{ demande.id_conge }}" href="#modalRefus">Refuser</a>


                                        <br><br>
                                        <a class="modalHistorique modal-trigger" data-id="{{ demande.collabo|json_encode }}" href="#modalHistorique">Historique des congés</a>

                                    </div>

                                </li>
                            </ul>
                        {% endfor%}
                    {% endif %}
                </div>
                <div id="HistoriqueDemandes" class="col s12">
                    {% if congesPassees == null %}
                        Historique vide
                    {% else %}
                        {% for conge in congesPassees %}
                            <ul class="collapsible">
                                <li>
                                    <div class="collapsible-header" style="display: block">
                                        <div class="right">
                                            <img class="responsive-img"  height="50" width="50" src="{{ conge.collabo.profile_pic_path }}"/>
                                        </div>
                                        {{ conge.collabo.prenom }} {{ conge.collabo.nom }} <br>
                                        {{ conge.type }} <br>
                                        {{ conge.date_debut|date('d/m/Y') }} - {{ conge.date_fin|date('d/m/Y') }}<br>
                                        {{ conge.statut }} <br>
                                        {% if conge.commentaire != null %}
                                            Motif : {{ conge.commentaire }}
                                        {% endif %}

                                    </div>
                                </li>
                            </ul>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>

        <div id="modalHistorique" class="modal">
            <div class="modal-content">
                <h4>Historique des demandes</h4>
            </div>
            <div class="modal-footer">
                <a href="#!" class="modal-close waves-effect waves-green btn-flat">Quitter</a>
            </div>
        </div>

        <div id="modalRefus" class="modal">
            <div class="row">
                <form method="post" action="{{ path('valider.conges.chef') }}">
                    <div class="modal-content">
                        <h4>Refus de la demande de conges</h4>
                        <input type="hidden" name="decision" value="refuser"/>
                        <input type="hidden" name="demande" id="demande">
                        <textarea id="motif" name="motif" class="materialize-textarea"></textarea>
                        <label for="motif">Motif de refus</label>

                    </div>
                    <div class="modal-footer">
                        <div class="col s6 center-align">
                            <a href="#!" class="modal-close waves-effect waves-light btn red" style="margin:auto;">Annuler</a>
                        </div>
                        <div class="col s6 center-align">
                            <button type="submit" class="waves-effect waves-light btn green" style="margin:auto;">Valider</button>
                        </div>

                    </div>
                </form>
            </div>
        </div>
{% endblock %}

{% block javascripts %}
    <script src='/js/plugins/fullcalendar/lib/moment.min.js' type="text/javascript"></script>
    <script src='/js/plugins/fullcalendar/js/fullcalendar.min.js' type="text/javascript"></script>
    <script src="/js/plugins/fullcalendar/fullcalendar-script.js" type="text/javascript"></script>
    <script>
        $(document).ready(function(){
            $('.tabs').tabs();
            $('.collapsible').collapsible();
            $('.modal').modal();
            $(document).on("click", ".modalHistorique", function () {
                alert(data.result);
            });

            $(document).on("click", ".modalRefus", function () {
                var data = $(this).data('id');
                $(".modal-content #demande").val( data );

            });
        });
    </script>
{% endblock %}

templates/pages/gestionDemandesAvance.html.twig
{% extends 'topBar.html.twig' %}

{% block title %}Gestion demandes d'avance {% endblock %}
{% block body %}
    <div class="row">
        <div class="col s12 m12 l6">
            <ul class="collection with-header">
                <li class="collection-header"><h4>Demandes en attente</h4></li>
                {% for demande in demandesEnAttente %}
                    <a class="waves-effect waves-light" href="{{ path('gestionDemandes.details', {id: demande.id}) }}">
                    <li class="collection-item">
                        <div>

                            Demande de {{ demande.collabo.nom }} {{ demande.collabo.prenom }} pour {{ demande.montant }} euros.<br>
                            Motif : {{ demande.motif }} <br>
                            Lignes concernées :<br>
                            {% for ligne in demande.lignes %}
                                <span>&#8226;</span> {{ ligne.mission }} - {{ ligne.intitule }} : {{ ligne.montant }} euros<br>
                                &nbsp; &nbsp; Demande d'avance de {{ ligne.montantAvance }} euros
                                <br>
                            {% endfor %}
                        </div>
                    </li>
                    </a>
                {% endfor %}
            </ul>
        </div>
        <div class="col s12 m12 l6">
            <ul class="collection with-header">
                <li class="collection-header"><h4>Historique des demandes</h4></li>
                {% for demande in demandesPassees %}
                    <li class="collection-item">
                    <div>

                        Demande de {{ demande.collabo.nom }} {{ demande.collabo.prenom }} pour {{ demande.montant }} euros.<br>
                        Motif : {{ demande.motif }} <br>
                        Lignes concernées :<br>
                        {% for ligne in demande.lignes %}
                            <span>&#8226;</span> {{ ligne.mission }} - {{ ligne.intitule }} : {{ ligne.montant }} euros<br>
                            Demande d'avance de {{ ligne.montantAvance }} euros
                            <br>
                        {% endfor %}
                        Décision : <b>{{ demande.statut }}</b>
                    </div>
                    </li>
                {% endfor %}

            </ul>
        </div>
    </div>
{% endblock %}

templates/pages/gestionDemandesAvanceDetails.html.twig
{% extends 'topBar.html.twig' %}

{% block title %}Gestion demandes d'avance {% endblock %}
{% block body %}
    <div class="row">
        <div class="col s10 m10 ll0 push-l1 push-s1 push-m1">
            <ul class="collection with-header">
                <li class="collection-header">
                    <h4>Demande d'avance de {{ demande.collabo.nom }} {{ demande.collabo.prenom }}</h4><br>
                    Date de la demande : {{ demande.lastModif|date("d/m/Y") }} <br>
                    Montant demandé : {{ demande.montant }} euros<br>
                    Motif invoqué : {{ demande.motif }}<br>
                </li>
                {% for ligne in demande.lignes %}
                <li class="collection-item">
                    {{ ligne.mission }} {{ ligne.intitule }} <br>
                    Montant estimé : {{ ligne.montant }}<br>
                    Montant demandé : {{ ligne.montantAvance }} <br>
                    Date d'ajout de la ligne : {{ ligne.date|date("d/m/Y") }}<br>
                    Projet rattaché : {{ ligne.projet.nom }}
                </li>
                {% endfor %}
                <li class="collection-item">
                    <a href="{{ path('gestionDemandes.choix', {choix: false, id: demande.id}) }}" class="waves-effect waves-light btn-large red">Refuser la demande</a>
                    <a href="{{ path('gestionDemandes.choix', {choix: true, id: demande.id}) }}" class="waves-effect waves-light btn-large green">Accepter la demande</a>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

templates/pages/gestionNotesFraisDetails.html.twig
{% extends 'topBar.html.twig' %}
{% block title %}Detail Note de Frais{% endblock %}
{% block body %}
    <div class="row p-2">
        <h5 class="p-1 center-align">Détails de la note de frais <b>{{ noteDeFrais.collabo.nom }} {{ noteDeFrais.collabo.prenom }}</b> du <b>{{ noteDeFrais.mois }}-{{ noteDeFrais.annee }}</b></h5>
        {%  if  noteDeFrais.statut == statusNotes[2] or noteDeFrais.statut == statusNotes[9] %}
        <form method="post" action="{{ path('validation.lignes.details') }}">
        {% endif %}
            {% set montantTotal = 0 %}
            <div class="row col s10 blue lighten-4 m-0 p-2 center-align ">
                <div class="col s2"><b>Intitulé</b></div>
                <div class="col s2"><b>Projet</b></div>
                <div class="col s1"><b>Montant</b></div>
                <div class="col s2"><b>Type</b></div>
                <div class="col s2"><b>Date</b></div>
                <div class="col s2"><b>Status</b></div>
                <div class="col s1">Avance</div>
            </div>
            <div class="row col s1 red lighten-4 center-align m-0"><b>Refuser</b></div>
            <div class="row col s1 green lighten-4 center-align m-0"><b>Accepter</b></div>

            {% if ligneDeFrais is empty %}
                <h5 class="center-align p-2">Cette note n'a pas de lignes associées</h5>
            {% endif %}
            {% for ligne in ligneDeFrais %}
                <ul class="collapsible col s10 row m-0">
                    {% set montantTotal = montantTotal + ligne.montant %}
                    <li>
                        <div class="collapsible-header row m-0 center-align">
                            <div class="col s2">{{ ligne.intitule }}</div>
                            <div class="col s2">{{ ligne.projet }}</div>
                            <div class="col s1">{{ ligne.montant }}€</div>
                            <div class="col s2">{{ ligne.type }}</div>
                            <div class="col s2">{{ ligne.date|date("Y-m-d") }}</div>
                            <div class="col s2">{{ ligne.statutValidation }}</div>
                            <div class="col s1">
                                {% if ligne.avance %}
                                    A
                                {% endif %}
                            </div>
                        </div>
                        <div class="collapsible-body row m-0">
                            <div class="col s8 valign-wrapper">
                                <p style="margin-right:5%;"><b>Justificatif:</b></p>
                                {% if ligne.justificatif is empty %}
                                    <span> Il n'y a pas de justificatif associé à cette ligne</span>
                                {% else %}
                                    {% for justi in ligne.justificatif %}
                                        {% if justi == "Perdu" %}
                                            <div class="card orange">
                                                <div class="card-content white-text">
                                                    <span>Justificatif perdu</span>
                                                </div>
                                            </div>
                                        {% else %}
                                            <div class="card" style="margin-right:20px;">
                                                <div class="card-image p-1">
                                                    <img id="imageProfil" src="/{{ justi }}" class="responsive-img" style="width:100px; margin:auto;"/>
                                                </div>
                                                <div class="card-content p-1">
                                                    <span>{{ justi|split('/')|last }}</span>
                                                </div>
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </li>
                </ul>
                <label class="collapsible col s1 center-align z-depth-0" style="border-color:transparent;">
                    <input name="{{ligne.id}}"  value="refus" type="radio" required="required" 
                            {% if ligne.statutValidation != statusNotes[2] %}
                                disabled="disabled"
                            {% endif %}
                            /><span></span>
                </label>
                <label class="collapsible col s1 center-align z-depth-0" style="border-color:transparent;">
                    <input name="{{ ligne.id }}" value="accept" type="radio" required="required"
                            {% if ligne.statutValidation != statusNotes[2] %}
                                disabled="disabled"
                            {% endif %}
                            /><span></span>
                </label>
            {% endfor %}

            <div class="secondary-content col s12 m-2">
                <a href="{{ path('app_gestionNotesDeFrais') }}" class="waves-effect waves-light btn red left"><i class="material-icons left">clear</i>Annuler</a>
                {%  if  noteDeFrais.statut == statusNotes[2] or noteDeFrais.statut == statusNotes[9] %}
                    <input type="hidden" id="id" name="id" value="{{ noteDeFrais.id }}"/>
                    <button id="id1" class="btn green waves-effect waves-light right">Confirmer</button>
                {% endif %}
            </div>
        </form>
        
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(function(){
            $('.collapsible').collapsible();
        });
        $(document).ready(function(){
            $('.modal').modal();
        });
        $(document).ready(function(){
            $('.tooltipped').tooltip();
        });
    </script>
{% endblock %}