src/Entity/Collaborateur.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\EquatableInterface;
/**
 * @ORM\Entity(repositoryClass="App\Repository\CollaborateurRepository")
 */
class Collaborateur implements UserInterface,EquatableInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    public $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $salt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $roles;

    /**
     * @ORM\Column(type="string", length=1024, nullable=true)
     */
    private $profile_pic_path;

    /**
     * @ORM\Column(type="string", length=1024, nullable=true)
     */
    private $background_pic_path;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Service")
     * @ORM\JoinColumn(nullable=true)
     */
    public $service;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Service")
     */
    public $ServiceChef;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Projet")
     */
    private $projets;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    public $email;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Notification", mappedBy="collaborateur")
     */
    private $notifications;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $role_entreprise;

    /**
     * @ORM\Column(type="integer")
     */
    public $rtt;

    /**
     * @ORM\Column(type="integer")
     */
    public $conge;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Conge", mappedBy="collabo")
     */
    public $conges;

    const STATUS = [
        0 => 'Collaborateur',
        1 => 'Chef de service',
        2 => 'directeur',
    ];

    public function __construct()
    {
        $this->ServiceChef = new ArrayCollection();
        $this->projets = new ArrayCollection();
        $this->setRoles('ROLE_USER');
        $this->setRoleEntreprise(Collaborateur::STATUS[0]);
        $this->setSalt('');
        $this->setProfilePicPath('images/profile_pics/anonym_picture.jpg');
        $this->setBackgroundPicPath('images/profile_pics/backgroundProfil.png');

        $this->notifications = new ArrayCollection();
        $this->conges = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getRoles()
    {
        return [
            $this->roles
        ];
    }

    public function setRoles(string $roles):self
    {
        $this->roles = $roles;
        return $this;
    }

    public function getSalt()
    {
        return $this->salt;
    }

    public function setSalt(string $salt):self
    {
        $this->salt = $salt;
        return $this;
    }

    public function eraseCredentials()
    {
    }

    public function isEqualTo(UserInterface $user)
    {
      if (!$user instanceof Collaborateur) {
          return false;
      }

      if ($this->password !== $user->getPassword()) {
          return false;
      }

      if ($this->salt !== $user->getSalt()) {
          return false;
      }

      if ($this->username !== $user->getUsername()) {
          return false;
      }

      return true;
    }

    public function getprofile_pic_path(): string
    {
        return $this->profile_pic_path;
    }

    public function setProfilePicPath(string $profile_pic_path): self
    {
        $this->profile_pic_path = $profile_pic_path;

        return $this;
    }

    public function getBackground_pic_path(): string
    {
        if($this->background_pic_path === NULL)
        {
          return "images/backgroundProfil.png";
        }
        return $this->background_pic_path;
    }

    public function setBackgroundPicPath(string $background_pic_path): self
    {
        $this->background_pic_path = $background_pic_path;

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->service;
    }

    public function setService(?Service $service): self
    {
        $this->service = $service;

        return $this;
    }

    /**
     * @return Collection|Service[]
     */
    public function getServiceChef(): Collection
    {
        return $this->ServiceChef;
    }

    public function addServiceChef(Service $serviceChef): self
    {
        if (!$this->ServiceChef->contains($serviceChef)) {
            $this->ServiceChef[] = $serviceChef;
        }

        return $this;
    }

    public function removeServiceChef(Service $serviceChef): self
    {
        if ($this->ServiceChef->contains($serviceChef)) {
            $this->ServiceChef->removeElement($serviceChef);
        }

        return $this;
    }

    /**
     * @return Collection|Projet[]
     */
    public function getProjets(): Collection
    {
        return $this->projets;
    }


    public function addProjet(Projet $projet): self
    {
        if (!$this->projets->contains($projet)) {
            $this->projets[] = $projet;
        }

        return $this;
    }

    public function removeProjet(Projet $projet): self
    {
        if ($this->projets->contains($projet)) {
            $this->projets->removeElement($projet);
            // set the owning side to null (unless already changed)
        }
        return $this;
    }





    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|Notification[]
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications[] = $notification;
            $notification->setCollaborateur($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): self
    {
        if ($this->notifications->contains($notification)) {
            $this->notifications->removeElement($notification);
            // set the owning side to null (unless already changed)
            if ($notification->getCollaborateur() === $this) {
                $notification->setCollaborateur(null);
            }
        }

        return $this;
    }

    public function getRoleEntreprise(): ?string
    {
        return $this->role_entreprise;
    }

    public function getrole_entreprise(): ?string
    {
        return $this->role_entreprise;
    }

    public function setRoleEntreprise(string $role_entreprise): self
    {
        $this->role_entreprise = $role_entreprise;

        return $this;
    }

    public function getRtt(): ?int
    {
        return $this->rtt;
    }

    public function setRtt(int $rtt): self
    {
        $this->rtt = $rtt;

        return $this;
    }

    public function getConge(): ?int
    {
        return $this->conge;
    }

    public function setConge(int $conge): self
    {
        $this->conge = $conge;

        return $this;
    }

    /**
     * @return Collection|Conge[]
     */
    public function getConges(): Collection
    {
        return $this->conges;
    }

    public function addConge(Conge $conge): self
    {
        if (!$this->conges->contains($conge)) {
            $this->conges[] = $conge;
            $conge->setCollabo($this);
        }

        return $this;
    }

    public function removeConge(Conge $conge): self
    {
        if ($this->conges->contains($conge)) {
            $this->conges->removeElement($conge);
            // set the owning side to null (unless already changed)
            if ($conge->getCollabo() === $this) {
                $conge->setCollabo(null);
            }
        }

        return $this;
    }
}

src/Entity/LigneDeFrais.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\DateType;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LigneDeFraisRepository")
 */
class LigneDeFrais
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    private $intitule;

    /**
     * @ORM\Column(type="string", length=2048)
     */
    private $mission;

    /**
     * @ORM\Column(type="float")
     */
    private $montant;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statutValidation;

    /**
     * @ORM\Column(type="boolean")
     */
    private $avance;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\NoteDeFrais")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Note;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Projet")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Projet;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastModif;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="array")
     */
    private $justificatif = [];

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $montantAvance;

    const STATUS = [
        0 => 'En cours',
        1 => 'En attente chef',
        2 => 'validee chef',
        3 => 'refusee chef',
        4 => 'En attente compta', #NOT USED
        5 => 'validee compta',
        6 => 'valideeExceptJustificatif',
        7 => 'refusee compta',
    ];

    public function __construct()
    {
      $this->statutValidation = "Non validée";
      $this->lastModif = new \DateTime();
      $this->avance = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): self
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getMission(): ?string
    {
        return $this->mission;
    }

    public function setMission(string $mission): self
    {
        $this->mission = $mission;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStatutValidation(): ?string
    {
        return $this->statutValidation;
    }

    public function setStatutValidation(string $statutValidation): self
    {
        $this->statutValidation = $statutValidation;

        return $this;
    }

    public function getAvance(): ?bool
    {
        return $this->avance;
    }

    public function setAvance(bool $avance): self
    {
        $this->avance = $avance;

        return $this;
    }

    public function getNote(): ?NoteDeFrais
    {
        return $this->Note;
    }

    public function setNote(?NoteDeFrais $Note): self
    {
        $this->Note = $Note;

        return $this;
    }

    public function getProjet(): ?Projet
    {
        return $this->Projet;
    }

    public function setProjet(?Projet $Projet): self
    {
        $this->Projet = $Projet;

        return $this;
    }

    public function getLastModif(): ?\DateTimeInterface
    {
        return $this->lastModif;
    }

    public function setLastModif(?\DateTimeInterface $lastModif): self
    {
        $this->lastModif = $lastModif;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getJustificatif(): ?array
    {
        return $this->justificatif;
    }

    public function setJustificatif(array $justificatif): self
    {
        $this->justificatif = $justificatif;

        return $this;
    }

    public function isModifiable(): ?bool
    {
        if(                                    $this->statutValidation == LigneDeFrais::STATUS[0] 
                                            || $this->statutValidation == LigneDeFrais::STATUS[3]
                                            || $this->statutValidation == LigneDeFrais::STATUS[7]
                                            || $this->statutValidation == LigneDeFrais::STATUS[6]){
            return true;
        }
        return false;
    }

    public function getMontantAvance(): ?float
    {
        return $this->montantAvance;
    }

    public function setMontantAvance(?float $montantAvance): self
    {
        $this->montantAvance = $montantAvance;

        return $this;
    }
}

src/Entity/Projet.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjetRepository")
 */
class Projet
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=512)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=2048, nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="date")
     */
    private $DateDebut;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $DateFin;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Collaborateur")
     */
    private $collabos;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Service")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Service;

    const STATUS = [
        0 => 'A venir',
        1 => 'En cours',
        2 => 'Suspendu',
        3 => 'Fini',
    ];

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    public function __construct()
    {
        $this->collabos = new ArrayCollection();
        $this->setStatus(Projet::STATUS[0]);
        $this->setDescription('Pas de description.');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(?\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }

    /**
     * @return Collection|Collaborateur[]
     */
    public function getCollabos(): Collection
    {
        return $this->collabos;
    }

    public function addCollabo(Collaborateur $collabo): self
    {
        if (!$this->collabos->contains($collabo)) {
            $this->collabos[] = $collabo;
            $collabo->addProjet($this);

        }

        return $this;
    }

    public function removeCollabo(Collaborateur $collabo): self
    {
        if ($this->collabos->contains($collabo)) {
            $this->collabos->removeElement($collabo);
        }

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->Service;
    }

    public function setService(?Service $Service): self
    {
        $this->Service = $Service;

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;
        return $this;
    }
}

templates/pages/gestionMissions/gestionMissionsDetails.html.twig
{% extends 'topBar.html.twig' %}
{% block title %} {{ mission.nom }} {% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <ul class="collection with-header">
                <li class="collection-header blue lighten-5 row">
                    <div class="col s12">
                        <h4 class="center-align">{{ mission.nom }}</h4>
                    </div>
                    <div class="col s5">
                        <b>Dates:</b>
                        <span class="center-align">{{ mission.DateDebut|date('d/m/Y') }} - {{ mission.DateFin|date('d/m/Y') }}</span>
                    </div>
                    <div class="col s5">
                        <b>Status:</b>
                        <span class="center-align">{{ mission.status }}</span>
                    </div>
                    <div class="col s2">
                        <b>ID:</b>
                        <span class="center-align">{{ mission.id }}</span>
                    </div>

                    <div class="col s12">
                        <b>Service:</b>
                        <span class="center-align">{{ mission.Service }}</span>
                    </div>
                    
                    <div class="col s12 m-2">
                        <b>Description</b>
                        <p>{{ mission.Description }}</p>
                    </div>
                </li>
                {% if lignesATraiter == null  %}
                    <li class="collection-item">
                        Vous n'avez aucune ligne à traiter pour cette mission.
                    </li>
                {% else %}
                    {% for ligne in lignesATraiter %}
                        <li class="collection-item">
                            <div class="secondary-content">
                                Collaborateur : {{ ligne.note.collabo.nom }} {{ ligne.note.collabo.prenom }}
                            </div>
                            {{ ligne.intitule }} <br>
                            Montant : {{ ligne.montant }} <br>
                            Type : {{ ligne.type }}<br>
                            {% if ligne.justificatif is empty %}
                                <span> Il n'y a pas de justificatif associé à cette ligne</span>
                            {% else %}
                                {% for justi in ligne.justificatif %}
                                    {% if justi == "Perdu" %}
                                        <div class="card orange">
                                            <div class="card-content white-text">
                                                <span>Justificatif perdu</span>
                                            </div>
                                        </div>
                                    {% else %}
                                        <div class="card" style="margin-right:5px;">
                                            <div class="card-image p-1">
                                                <img id="imageProfil" src="/{{ justi }}" class="responsive-img" style="width:100px; margin:auto;"/>
                                            </div>
                                            <div class="card-content p-1">
                                                <span>{{ justi|split('/')|last }}</span>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}


                            <div class="secondary-content">
                                <form action="{{ path('valider.ligne') }}" method="post">
                                    <input type="hidden" name="ligne" value="{{ ligne.id }}"/>
                                    <input type="hidden" name="mission" value="{{ mission.id }}"/>
                                    <input type="hidden" name="decision" id="decision" value=""/>
                                    <button type="submit" onclick="$('#decision').val('refuser');" class="waves-effect waves-light btn-small red" style="margin:auto;">Refuser</button>
                                    <button type="submit" onclick="$('#decision').val('valider');" class="waves-effect waves-light btn-small green" style="margin:auto;">Valider</button>
                                </form>
                            </div>
                        </li>

                    {% endfor %}
                {% endif %}
                <li class="collection-item">
                    <a class="waves-effect waves-light btn modal-trigger green" href="#ajoutCollaborateur" >Ajouter un collaborateur</a>
                    <a class="waves-effect waves-light btn modal-trigger red" href="#supprimerCollaborateur" >Supprimer un collaborateur</a>
                </li>
            </ul>
        </div>
    </div>

    <div id="ajoutCollaborateur" class="modal">
        <div class="row">
            <form method="post" action="{{ path('ajout.collabos') }}" class="col s12">
                <div class="modal-content">
                    <ul class="collection">
                        {% for collaborateur in collabosPasProjet %}
                        <li class="collection-item">
                            {{ collaborateur.nom }} {{ collaborateur.prenom }} - {{ collaborateur.service.nom }} : {{ collaborateur.roleEntreprise }}
                            <div class="secondary-content">
                                <div class="switch">
                                    <label>
                                        <input name="choix[]" value="{{ collaborateur.id }}" type="checkbox"/>
                                        <span class="lever"></span>
                                        Ajout au projet
                                    </label>
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                    <input type="hidden" name="projet" value="{{ mission.id }}"/>
                </div>
                <div class="modal-footer">
                    <div class="col s6 center-align">
                        <a href="#!" class="modal-close waves-effect waves-light btn red" style="margin:auto;">Annuler</a>
                    </div>
                    <div class="col s6 center-align">
                        <button type="submit" class="waves-effect waves-light btn green" style="margin:auto;">Valider</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div id="supprimerCollaborateur" class="modal">
        <div class="row">
            <form method="post" action="{{ path('suppression.collabos') }}" class="col s12">
                <div class="modal-content">
                    <ul class="collection">
                        {% for collaborateur in collabosProjet %}
                            <li class="collection-item">
                                {{ collaborateur.nom }} {{ collaborateur.prenom }} - {{ collaborateur.service.nom }} : {{ collaborateur.roleEntreprise }}
                                <div class="secondary-content">
                                    <div class="switch">
                                        <label>
                                            <input name="choix[]" value="{{ collaborateur.id }}" type="checkbox"/>
                                            <span class="lever"></span>
                                            Suppression du projet
                                        </label>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                    <input type="hidden" name="projet" value="{{ mission.id }}"/>
                </div>
                <div class="modal-footer">
                    <div class="col s6 center-align">
                        <a href="#!" class="modal-close waves-effect waves-light btn red" style="margin:auto;">Annuler</a>
                    </div>
                    <div class="col s6 center-align">
                        <button type="submit" class="waves-effect waves-light btn green" style="margin:auto;">Valider</button>
                    </div>
                </div>
            </form>
        </div>
    </div>




{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(function() {
            $('.modal').modal();
        });
    </script>
{% endblock %}

templates/pages/gestionMissions/gestionMissionsHome.html.twig
{% extends 'topBar.html.twig' %}
{% block title %} Gestion des missions {% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col s12 m4 l4 push-l4 push-m4">
                <a class="waves-effect waves-light btn modal-trigger" href="#modalAjout">Ajouter une mission</a>
            </div>
        </div>
        <div class="row">
            {% for mission in missions %}
                <div class="col s12 m4 l4">
                    <div class="card blue-grey darken-1">
                        <div class="card-content white-text">
                            <span class="card-title">{{ mission.nom }}</span>
                            <p>{{ mission.description }}</p>
                        </div>
                        <div class="card-action">
                            <a class="modalAjout modal-trigger" data-id="{{ mission.id }}/{{ mission.nom }}/{{ mission.description }}/{{ mission.dateDebut|date("Y-m-d") }}/{{ mission.dateFin|date("Y-m-d") }}" href="#modalAjout"><i class="material-icons">edit</i></a>
                            <a href="{{ path('gestion.mission.collabos',{id: mission.id}) }}"><i class="material-icons">person_add</i></a>
                            <a href="{{ path('gestion.mission.lignes',{id: mission.id}) }}" ><i class="material-icons">euro_symbol</i></a>
                            <a href="#" ><i class="material-icons">timer</i></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div id="modalAjout" name="modalAjout" class="modal">
        <div class="row">
            <form method="post" action="{{ path('ajout.Mission') }}" class="col s12">
                <div class="modal-content">
                    <div class="row">
                        <div class="input-field col s6">
                            <input placeholder="Nom du projet" id="nom" name="nom" type="text" class="validate" required>
                            <label for="nom">Nom</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <textarea placeholder="description du projet" id="description" name="description" class="materialize-textarea"></textarea>

                        </div>
                    </div>
                    <div class="row">
                        <input id="dateDebut" name="dateDebut" type="text" class="col s12 datepicker" required>
                        <label for="dateDebut">Date de début</label>
                    </div>
                    <div class="row">
                        <input id="dateFin" name="dateFin" type="text" class="col s12 datepicker" required>
                        <label for="dateFin">Date de fin</label>
                    </div>
                    <input type="hidden" id="id" name="id"/>
                </div>
                <div class="modal-footer">
                    <div class="col s6 center-align">
                        <a href="#!" class="modal-close waves-effect waves-light btn red" onclick="remove()" style="margin:auto;">Annuler</a>
                    </div>
                    <div class="col s6 center-align">
                        <button type="submit" class="waves-effect waves-light btn green" style="margin:auto;">Valider</button>
                    </div>
                </div>
            </form>
        </div>
    </div>


    <div class="js-user-rating" data-time="{{ dateActuelle|date("Y-m-d")}}">
        <!-- ... -->
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        var time = $('.js-user-rating').data('time');

        function remove() {
            $(".modal-content #id").val( null );
            $(".modal-content #nom").val( null );
            $(".modal-content #description").val( null );
            $(".modal-content #dateDebut").val( null );
            $(".modal-content #dateFin").val( null );
        }

        $(document).ready(function(){
            $('.modal').modal({
                onCloseEnd: remove(),
                onCloseStart: remove(),
            });
            $('.datepicker').datepicker({
                format: 'yyyy-mm-dd',
                container: document.getElementById("modalAjout"),
                autoClose: true,
                //minDate: new Date(2019, 10 - 1, 25),
            });
        });
    </script>

    <script>
        $(document).on("click", ".modalAjout", function () {
            var data = $(this).data('id').split('/');
            $(".modal-content #id").val( data[0] );
            $(".modal-content #nom").val( data[1] );
            $(".modal-content #description").val( data[2] );
            $(".modal-content #dateDebut").val( data[3] );
            $(".modal-content #dateFin").val( data[4] );

        });

    </script>

{% endblock %}