src/Entity/Collaborateur.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\EquatableInterface;
/**
 * @ORM\Entity(repositoryClass="App\Repository\CollaborateurRepository")
 */
class Collaborateur implements UserInterface,EquatableInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    public $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $salt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $roles;

    /**
     * @ORM\Column(type="string", length=1024, nullable=true)
     */
    private $profile_pic_path;

    /**
     * @ORM\Column(type="string", length=1024, nullable=true)
     */
    private $background_pic_path;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Service")
     * @ORM\JoinColumn(nullable=true)
     */
    public $service;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Service")
     */
    public $ServiceChef;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Projet")
     */
    private $projets;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    public $email;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Notification", mappedBy="collaborateur")
     */
    private $notifications;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $role_entreprise;

    /**
     * @ORM\Column(type="integer")
     */
    public $rtt;

    /**
     * @ORM\Column(type="integer")
     */
    public $conge;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Conge", mappedBy="collabo")
     */
    public $conges;

    const STATUS = [
        0 => 'Collaborateur',
        1 => 'Chef de service',
        2 => 'directeur',
    ];

    public function __construct()
    {
        $this->ServiceChef = new ArrayCollection();
        $this->projets = new ArrayCollection();
        $this->setRoles('ROLE_USER');
        $this->setRoleEntreprise(Collaborateur::STATUS[0]);
        $this->setSalt('');
        $this->setProfilePicPath('images/profile_pics/anonym_picture.jpg');
        $this->setBackgroundPicPath('images/profile_pics/backgroundProfil.png');

        $this->notifications = new ArrayCollection();
        $this->conges = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getRoles()
    {
        return [
            $this->roles
        ];
    }

    public function setRoles(string $roles):self
    {
        $this->roles = $roles;
        return $this;
    }

    public function getSalt()
    {
        return $this->salt;
    }

    public function setSalt(string $salt):self
    {
        $this->salt = $salt;
        return $this;
    }

    public function eraseCredentials()
    {
    }

    public function isEqualTo(UserInterface $user)
    {
      if (!$user instanceof Collaborateur) {
          return false;
      }

      if ($this->password !== $user->getPassword()) {
          return false;
      }

      if ($this->salt !== $user->getSalt()) {
          return false;
      }

      if ($this->username !== $user->getUsername()) {
          return false;
      }

      return true;
    }

    public function getprofile_pic_path(): string
    {
        return $this->profile_pic_path;
    }

    public function setProfilePicPath(string $profile_pic_path): self
    {
        $this->profile_pic_path = $profile_pic_path;

        return $this;
    }

    public function getBackground_pic_path(): string
    {
        if($this->background_pic_path === NULL)
        {
          return "images/backgroundProfil.png";
        }
        return $this->background_pic_path;
    }

    public function setBackgroundPicPath(string $background_pic_path): self
    {
        $this->background_pic_path = $background_pic_path;

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->service;
    }

    public function setService(?Service $service): self
    {
        $this->service = $service;

        return $this;
    }

    /**
     * @return Collection|Service[]
     */
    public function getServiceChef(): Collection
    {
        return $this->ServiceChef;
    }

    public function addServiceChef(Service $serviceChef): self
    {
        if (!$this->ServiceChef->contains($serviceChef)) {
            $this->ServiceChef[] = $serviceChef;
        }

        return $this;
    }

    public function removeServiceChef(Service $serviceChef): self
    {
        if ($this->ServiceChef->contains($serviceChef)) {
            $this->ServiceChef->removeElement($serviceChef);
        }

        return $this;
    }

    /**
     * @return Collection|Projet[]
     */
    public function getProjets(): Collection
    {
        return $this->projets;
    }


    public function addProjet(Projet $projet): self
    {
        if (!$this->projets->contains($projet)) {
            $this->projets[] = $projet;
        }

        return $this;
    }

    public function removeProjet(Projet $projet): self
    {
        if ($this->projets->contains($projet)) {
            $this->projets->removeElement($projet);
            // set the owning side to null (unless already changed)
        }
        return $this;
    }





    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|Notification[]
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications[] = $notification;
            $notification->setCollaborateur($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): self
    {
        if ($this->notifications->contains($notification)) {
            $this->notifications->removeElement($notification);
            // set the owning side to null (unless already changed)
            if ($notification->getCollaborateur() === $this) {
                $notification->setCollaborateur(null);
            }
        }

        return $this;
    }

    public function getRoleEntreprise(): ?string
    {
        return $this->role_entreprise;
    }

    public function getrole_entreprise(): ?string
    {
        return $this->role_entreprise;
    }

    public function setRoleEntreprise(string $role_entreprise): self
    {
        $this->role_entreprise = $role_entreprise;

        return $this;
    }

    public function getRtt(): ?int
    {
        return $this->rtt;
    }

    public function setRtt(int $rtt): self
    {
        $this->rtt = $rtt;

        return $this;
    }

    public function getConge(): ?int
    {
        return $this->conge;
    }

    public function setConge(int $conge): self
    {
        $this->conge = $conge;

        return $this;
    }

    /**
     * @return Collection|Conge[]
     */
    public function getConges(): Collection
    {
        return $this->conges;
    }

    public function addConge(Conge $conge): self
    {
        if (!$this->conges->contains($conge)) {
            $this->conges[] = $conge;
            $conge->setCollabo($this);
        }

        return $this;
    }

    public function removeConge(Conge $conge): self
    {
        if ($this->conges->contains($conge)) {
            $this->conges->removeElement($conge);
            // set the owning side to null (unless already changed)
            if ($conge->getCollabo() === $this) {
                $conge->setCollabo(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Connexion{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="/css/HomePage.css">
        <!-- bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
         integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="icon" type="image/png" href="images/logo_sans_texte.png" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        {% block stylesheets %}
          <link href="{{ asset('public/materialize/css/materialize.css') }}" rel="stylesheet"/>
          <link href="{{ asset('css/your_form_theme.css') }}" rel="stylesheet"/>
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}

        {% endblock %}
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="/materialize/js/materialize.min.js" ></script>

        <!-- bootstrap -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
          integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
          integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>


    </body>
</html>

templates/base2.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}DefaultNamePage{% endblock %}</title>
        <link type="text/css" rel="stylesheet" href="materialize/css/materialize.css"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="css/content.css"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="icon" type="image/png" href="images/logo_sans_texte.png" />
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <nav class="nav-extended navbar-fixed grey lighten-4">
          <div class="nav-wrapper">
            <ul class="hide-on-med-and-down row">
              <li class="col s12 m4 l2">
                <a href="{{ path('app_homepage') }}" class="brand-logo"><img src="images/logo.png" style="width:110px;height:45px;"></a>
              </li>
              <!-- Barre de recherche -->
              <li class="col s12 m4 l8">
                <div class="col s2"></div>
                <div class="input-field center-align col s6">
                  <i class="material-icons prefix">account_circle</i>
                  <input id="search" type="text" class="validate">
                  <label for="search">Rechercher un collaborateur</label>
                </div>
                <div class="col s2"</div>
              </li>
              <li class="col s12 m4 l2">
                <a class='dropdown-trigger btn btn-large' href='#' data-target='dropdown1'><b>{{app.user.nom}}</b> {{app.user.prenom}}</a>
              </li>
            </ul>
          </div>
          <div class="nav-content">
            <a class="btn-flat waves-effect waves-light btn-large" href="{{ path('app_noteFrais') }}" name="action">Mes notes de frais
              <i class="material-icons right">book</i>
            </a>
            <a class="btn-flat waves-effect waves-light btn-large"  href="{{ path('app_noteFrais') }}"  name="action">Mes demandes de congés
              <i class="material-icons right">perm_contact_calendar</i>
            </a>
            <button class="btn-flat waves-effect waves-light btn-large" href="{{ path('app_noteFrais') }}"  name="action">Mes demandes d'information
              <i class="material-icons right">send</i>
            </button>
          </div>
        </nav>
        <!-- Dropdown Structure -->
        <ul id='dropdown1' class='dropdown-content'>
          <li><a href="#!">Edition de profil</a></li>
          <li><a href="#!">Paramètres</a></li>
          <li class="divider" tabindex="-1"></li>
          <li><a href="/logout">Deconnexion</a></li>
        </ul>
        {% block body %}

        {% endblock %}

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script type="text/javascript" src="materialize/js/materialize.min.js"></script>
        <script src="https://rawgit.com/aurelia-ui-toolkits/aurelia-materialize-bundles/0.20.2/config2.js"></script>
        <script>
          System.import('aurelia-bootstrapper');
        </script>
        
        <script>
          $('.dropdown-trigger').dropdown();
        </script>

        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/card.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}DefaultNamePage{% endblock %}</title>
        <link type="text/css" rel="stylesheet" href="materialize/css/materialize.css"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="css/content.css"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="icon" type="image/png" href="images/logo_sans_texte.png" />
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <nav class="nav-extended navbar-fixed grey lighten-4">
          <div class="nav-wrapper">
            <ul class="hide-on-med-and-down row">
              <li class="col s12 m4 l2">
                <a href="{{ path('app_homepage') }}" class="brand-logo"><img src="images/logo.png" style="width:110px;height:45px;"></a>
              </li>
              <!-- Barre de recherche -->
              <li class="col s12 m4 l8">
                <div class="col s2"></div>
                <div class="input-field center-align col s6">
                  <i class="material-icons prefix grey-text text-darken-4">search</i>
                  <input id="search" type="text" class="validate">
                  <label for="search">Rechercher un collaborateur</label>
                </div>
                <div class="col s2"></div>
              </li>
              <li class="col s12 m4 l2">
                <a class='dropdown-trigger btn btn-large grey lighten-3 black-text' href='#' data-target='dropdown1'>
                  <i class='material-icons left'>
                    <img src="{{app.user.profile_pic_path}}" class="circle responsive-img" style="width:35px;height:35px;"/>
                  </i>
                  <b>{{app.user.nom}}</b>
                  {{app.user.prenom}}
                </a>
              </li>
            </ul>
          </div>
          <div class="nav-content">
            <a class="btn-flat waves-effect waves-light btn-large" href="{{ path('app_noteFrais') }}" name="action">Mes notes de frais
              <i class="material-icons right">book</i>
            </a>
            <a class="btn-flat waves-effect waves-light btn-large"  href="{{ path('app_noteFrais') }}"  name="action">Mes demandes de congés
              <i class="material-icons right">perm_contact_calendar</i>
            </a>
            <button class="btn-flat waves-effect waves-light btn-large" href="{{ path('app_noteFrais') }}"  name="action">Mes demandes d'information
              <i class="material-icons right">send</i>
            </button>
          </div>
        </nav>
        <!-- Dropdown Structure -->
        <ul id='dropdown1' class='dropdown-content'>
          <li><a href="#!">Edition de profil</a></li>
          <li><a href="#!">Paramètres</a></li>
          <li class="divider" tabindex="-1"></li>
          <li>
            <a href="/logout">
              <i class="material-icons prefix grey-text text-darken-4">keyboard_tab</i>
              Deconnexion
            </a>
          </li>
        </ul>
        {% block body %}

        {% endblock %}

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script type="text/javascript" src="materialize/js/materialize.min.js"></script>
        <script src="https://rawgit.com/aurelia-ui-toolkits/aurelia-materialize-bundles/0.20.2/config2.js"></script>
        <script>
          System.import('aurelia-bootstrapper');
        </script>
        
        <script>
          $('.dropdown-trigger').dropdown({
            coverTrigger: false
          });
        </script>

        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/topBar.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}DefaultNamePage{% endblock %}</title>
        <link type="text/css" rel="stylesheet" href="/materialize/css/materialize.css"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="/css/content.css"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="icon" type="image/png" href="/images/logo_sans_texte.png" />
        <link rel="stylesheet" type="text/css" href="/css/topBar.css">
        {% block stylesheets %}
            <link rel='stylesheet' href='fullcalendar/fullcalendar.css' />
        {% endblock %}
    </head>
    <body>
        <nav id="navBar" class="nav-extended navbar-fixed grey lighten-4">

          <div id="navWrapper" class="nav-wrapper">
            <ul id="rowtopBar" class="hide-on-med-and-down row">
              <div class="col s12 m4 l2">
                <a href="{{ path('app_homepage') }}" class="brand-logo"><img src="/images/logo.png" style="width:110px;height:45px;"></a>
              </div>
              <!-- Barre de recherche -->
              <div id="liSearch" class="col s12 m4 l7 ">
                  <div class="input-field">
                    <i id="iconSearch" class="material-icons prefix grey-text text-darken-4">search</i>
                    <input id="search" type="text" class="validate">
                    <label for="search" id="test" class="center-align">Rechercher un collaborateur</label>
                  </div>
              </div>

              <div id="liProfil" class="col s12 m4 l3">
                <a id="partProfil" class='dropdown-trigger btn btn-large grey lighten-5 black-text' href='#' data-target='dropdown1'>
                  <i id="iconPicture" class='material-icons left'>
                    <img id="imageProfil" src="/{{app.user.profile_pic_path}}" class="circle responsive-img" style="width:35px;height:35px;"/>
                  </i>
                  <b id="bProfil">{{app.user.nom}} {{app.user.prenom}}</b>

                </a>
              </div>
            </ul>
          </div>
          <div id="navContent" class="nav-content">
            <a id ="partNav" class="btn-flat waves-effect waves-light btn-large" href="{{ path('app_noteFrais') }}" name="action">Mes notes de frais
              <i class="material-icons right">book</i>
            </a>
            <a id ="partNav" class="col s4 m 4 l4 btn-flat waves-effect waves-light btn-large"  href="{{ path('app_calendarConges') }}"  name="action">Mes demandes de congés
              <i class="material-icons right">perm_contact_calendar</i>
            </a>
            <a id ="partNav" class="col s4 m 4 l4 btn-flat waves-effect waves-light btn-large" name="action">Mes demandes d'information
          <i class="material-icons right">send</i>
            </a>
            {% if app.user.roleEntreprise == 'Chef de service' %}
              <a class="btn-flat waves-effect waves-light btn-large" href="{{ path('app_gestionDemandesDeCongesChef') }}"  name="action">Gestion des congés du service
                <i class="material-icons right">beach_access</i>
              </a>
                <a class="btn-flat waves-effect waves-light btn-large" href="{{ path('app_gestionMissions') }}"  name="action">Gestion des missions
                    <i class="material-icons right">people</i>
                </a>
            {% endif %}
            {% if app.user.service.id == 2 %}
              <a class="btn-flat waves-effect waves-light btn-large" href="{{ path('app_gestionNotesDeFrais') }}"  name="action">Gestion des notes de frais
                <i class="material-icons right">local_atm</i>
              </a>
            {% endif %}
            {% if app.user.service.id == 1 %}
              <a class="btn-flat waves-effect waves-light btn-large" {#href="{{ path('app_gestionDemandesDInformation') }}"#}  name="action">Gestion des D. d'information
                <i class="material-icons right">assignment</i>
              </a>
                <a class="btn-flat waves-effect waves-light btn-large" href="{{ path('app_gestionDemandesDeCongesRH') }}"  name="action">Gestion des congés
                    <i class="material-icons right">beach_access</i>
                </a>
            {% endif %}
          </div>
        </nav>

        <!-- Dropdown Structure -->
        <ul id='dropdown1' class='dropdown-content'>
          <li><a href="{{ path('app_profile') }}">Edition de profil</a></li>
          <li><a href="#!">Paramètres</a></li>
          <li class="divider" tabindex="-1"></li>
          {% if is_granted('ROLE_ADMIN') %}
            <li><a href="{{ path('app_admin') }}">Paramètres administrateur</a></li>
          {% endif %}
          <li>
            <a href="/logout">
              <i class="material-icons prefix grey-text text-darken-4">keyboard_tab</i>
              Deconnexion
            </a>
          </li>
        </ul>
        {% block body %}

        {% endblock %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="/materialize/js/materialize.min.js"></script>
        <script src="https://rawgit.com/aurelia-ui-toolkits/aurelia-materialize-bundles/0.20.2/config2.js"></script>

        <script>
          $('.dropdown-trigger').dropdown({
            coverTrigger: false
          });
        </script>


        {% block javascripts %}
        {% endblock %}
        {% block researchBar %}
        {% endblock %}
    </body>
</html>